# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8213cfe71c225b9071d6a1c9e2e7aa46e51744974c75bbe35fb533ddab85466b7d530defe25e4113923df98073e1e16488b1474ed93ec5b13dbad1dbbca8ebf2

test:
  secret_key_base: a38c0e9c5e4b33462d92b1bf619ed671d14e7540d2a8b6a0426f6f19233969c0b4a31bb5aa437725fca2751f673dd7df54a85bb095221f91e976d3897aae512f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
